name: micahyaple
favicon: null
layout_spectrum: 1
typography_spectrum: 0.03322360501624644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c6c0ae'
    - '#47433d'
    - '#857e70'
  brandStrength: 1
  lightness: 0.18577685207128525
  saturation: 0.6462677996605635
  rhythmicContrast: 0.7875650934875011
purpose: []
